# Colors
RESET = \033[0m
GREEN = \033[32m
BLUE = \033[34m
YELLOW = \033[33m
RED = \033[31m

# Executables
PHILO = philo

# Compiler and Flags
CC = gcc
CFLAGS = -Werror -Wall -Wextra -g -I.

# Commands
RM = rm -rf

